import { createContext, useContext, Component, Suspense, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { Canvas,useFrame,useThree } from '@react-three/fiber';
import { ContactShadows,Edges,Html,OrbitControls,RoundedBox } from '@react-three/drei';
import type { OrbitControls as Controls } from 'three-stdlib';
import * as THREE from 'three';
import { AssemblyRoom } from '../viewer/AssemblyRoom';
import { useBuilderPreferences } from '../profile/preferences';
import { PIECES,SM_ACTIONS,evaluateAction,type Action,type Piece } from './timeline';
import type { AssemblyViewerProps } from '../viewer/AssemblyViewer';
const XrayContext=createContext(false);
function Panel({piece,highlighted,context}:{piece:Piece;highlighted:boolean;context:boolean}){
 const xray=useContext(XrayContext);
 const cable=piece.id==='desktop';const shape=useMemo(()=>{if(!cable)return null;const s=new THREE.Shape();s.moveTo(-.825,-.3);s.lineTo(.825,-.3);s.lineTo(.825,.3);s.lineTo(-.825,.3);s.closePath();const h=new THREE.Path();h.absarc(-.35,-.12,.035,0,Math.PI*2,true);s.holes.push(h);return s;},[cable]);
 return <><mesh castShadow receiveShadow rotation={cable?[Math.PI/2,0,0]:[0,0,0]} position={cable?[0,.0125,0]:[0,0,0]}>{shape?<extrudeGeometry args={[shape,{depth:.025,bevelEnabled:false,curveSegments:32}]} />:<boxGeometry args={piece.size}/>}<meshStandardMaterial color={context?'#d6dfe3':'#f5f3ee'} roughness={.4} transparent={context||xray} opacity={xray?.16:context?.28:1} depthWrite={!xray&&!context} emissive={highlighted?'#e9a43f':'#000'} emissiveIntensity={highlighted?.12:0}/>{highlighted&&<Edges color="#bc7921" threshold={22}/>}</mesh>{piece.holes?.filter(h=>!(cable&&h.radius>.02)).map((h,i)=><group key={i} position={h.at} rotation={h.axis==='x'?[0,0,-Math.PI/2]:h.axis==='z'?[Math.PI/2,0,0]:[0,0,0]}><mesh><cylinderGeometry args={[h.radius,h.radius,.0015,20]}/><meshBasicMaterial color="#334049" transparent={context} opacity={context?.4:1}/></mesh><mesh><torusGeometry args={[h.radius+.0007,.0004,6,20]}/><meshStandardMaterial color="#aaa9a3" roughness={.7}/></mesh></group>)}</>;
}
function Hardware({piece,highlighted}:{piece:Piece;highlighted:boolean}){
 const r=piece.size[0],len=piece.size[1];const thread=useMemo(()=>{if(!['bolt','hexscrew','dowel'].includes(piece.kind))return null;const pts=Array.from({length:161},(_,i)=>{const t=i/160,a=t*Math.PI*2*12;return new THREE.Vector3(Math.cos(a)*r*1.03,(t-.5)*len*.75,Math.sin(a)*r*1.03)});return new THREE.TubeGeometry(new THREE.CatmullRomCurve3(pts),160,r*.1,4,false);},[piece.kind,r,len]);useEffect(()=>()=>thread?.dispose(),[thread]);
 const color=piece.kind==='dowel'?'#c8ad7c':piece.kind==='cover'||piece.kind==='pad'?'#efefea':'#a5adb2';
 if(piece.kind==='ring')return <group><mesh rotation={[Math.PI/2,0,0]}><torusGeometry args={[r,.003,12,40]}/><meshStandardMaterial color="#ecebe6" roughness={.45}/></mesh><mesh><cylinderGeometry args={[r,r,.023,40,1,true]}/><meshStandardMaterial color="#ecebe6" side={THREE.DoubleSide}/></mesh></group>;
 if(piece.kind==='pad')return <RoundedBox args={piece.size} radius={.002} smoothness={2}><meshStandardMaterial color={color}/></RoundedBox>;
 return <group><mesh castShadow><cylinderGeometry args={[r,r,len,24]}/><meshStandardMaterial color={color} metalness={piece.kind==='dowel'||piece.kind==='cover'?0:.7} roughness={.35} emissive={highlighted?'#c69b52':'#000'} emissiveIntensity={highlighted?.12:0}/></mesh>{thread&&<mesh geometry={thread}><meshStandardMaterial color={piece.kind==='dowel'?'#ad8d57':'#6f7c85'} metalness={piece.kind==='dowel'?0:.7} roughness={.4}/></mesh>}
 {['bolt','hexscrew','cam','cover'].includes(piece.kind)&&<group position={[0,len/2,0]}><mesh><cylinderGeometry args={[r*(piece.kind==='cam'?1:1.65),r*1.4,.002,24]}/><meshStandardMaterial color={color} metalness={piece.kind==='cover'?0:.6} roughness={.35}/></mesh>{piece.kind==='hexscrew'?<mesh rotation={[-Math.PI/2,0,0]} position={[0,.0012,0]}><circleGeometry args={[r*.8,6]}/><meshBasicMaterial color="#3d4952"/></mesh>:piece.kind!=='cover'?<><mesh position={[0,.0013,0]}><boxGeometry args={[r*1.4,.0004,r*.3]}/><meshBasicMaterial color="#384751"/></mesh><mesh position={[0,.0013,0]}><boxGeometry args={[r*.3,.0004,r*1.4]}/><meshBasicMaterial color="#384751"/></mesh></>:null}</group>}
 {piece.kind==='cam'&&<mesh position={[r*.82,0,0]}><boxGeometry args={[r*.4,len*.7,r*.8]}/><meshBasicMaterial color="#47515a"/></mesh>}</group>;
}
function Tool({kind}:{kind:Piece['kind']}){
 if(kind==='hexkey')return <group><mesh position={[0,.018,0]}><cylinderGeometry args={[.003,.003,.075,6]}/><meshStandardMaterial color="#8495a2" metalness={.7}/></mesh><mesh position={[.024,.055,0]} rotation={[0,0,Math.PI/2]}><cylinderGeometry args={[.003,.003,.05,6]}/><meshStandardMaterial color="#8495a2" metalness={.7}/></mesh></group>;
 if(kind==='hammer')return <group><mesh position={[0,.04,0]}><cylinderGeometry args={[.008,.007,.15,12]}/><meshStandardMaterial color="#b58b56"/></mesh><RoundedBox args={[.075,.025,.027]} radius={.003} position={[0,.12,0]}><meshStandardMaterial color="#8a969d" metalness={.6}/></RoundedBox></group>;
 return <group><mesh position={[0,.055,0]}><cylinderGeometry args={[.012,.011,.08,16]}/><meshStandardMaterial color="#244b67" roughness={.4}/></mesh><mesh position={[0,-.025,0]}><cylinderGeometry args={[.003,.003,.085,12]}/><meshStandardMaterial color="#a3afb6" metalness={.8}/></mesh><mesh position={[0,-.069,0]}><boxGeometry args={[.004,.005,.0015]}/><meshStandardMaterial color="#80919d" metalness={.8}/></mesh></group>;
}
interface Playback {t:React.MutableRefObject<number>;playing:React.MutableRefObject<boolean>;invalidate:React.MutableRefObject<()=>void>;onTick:(n:number)=>void;speed:React.MutableRefObject<number>;}
function Scene({action,playback,inspect,close,controls,onPart}:{action:Action;playback:Playback;inspect:boolean;close:boolean;controls:React.MutableRefObject<Controls|null>;onPart:(text:string)=>void}){
 const objects=useRef<Record<string,THREE.Group>>({});const children=useMemo(()=>{const m:Record<string,Piece[]>={};for(const p of PIECES)(m[p.parent??'root']??=[]).push(p);return m;},[]);const currentIds=useMemo(()=>new Set(action.tracks.map(t=>t.id)),[action]);const guideLine=useMemo(()=>new THREE.Line(new THREE.BufferGeometry(),new THREE.LineDashedMaterial({color:"#398dc0",dashSize:.013,gapSize:.008})),[]);useEffect(()=>()=>{guideLine.geometry.dispose();(guideLine.material as THREE.Material).dispose();},[guideLine]);const marker=useRef<THREE.Mesh>(null);const label=useRef<THREE.Group>(null);const textRef=useRef<HTMLSpanElement>(null);const {camera,invalidate}=useThree();const auto=useRef(true);
 useEffect(()=>{const big=Number(action.id.split('-').at(-1))>=12;const target=new THREE.Vector3(...(close?action.focus:big?[0,.85,0]:[0,.36,0]));controls.current?.target.copy(target);camera.position.copy(target).add(new THREE.Vector3(...(close?[.24,.18,.28]:big?[2.8,1.5,3.1]:[1.7,1.25,2.1])));controls.current?.update();auto.current=true;invalidate();},[action.id,close,camera,controls,invalidate]);
 useEffect(()=>{const c=controls.current;if(!c)return;const start=()=>{auto.current=false;};c.addEventListener('start',start);return()=>c.removeEventListener('start',start);},[controls]);
 useFrame((_,raw)=>{const delta=raw>.2?1/60:raw;if(playback.playing.current&&!inspect)playback.t.current=Math.min(1,playback.t.current+delta*playback.speed.current/action.duration);if(playback.t.current>=1)playback.playing.current=false;playback.onTick(playback.t.current);const frame=evaluateAction(action,playback.t.current);if(inspect){const seen=new Set<string>();for(const track of action.tracks){if(seen.has(track.id))continue;seen.add(track.id);frame[track.id]=structuredClone(track.from);if(["driver","hammer","hexkey"].includes(track.id))frame[track.id].visible=false;}}for(const p of PIECES){const obj=objects.current[p.id],v=frame[p.id];if(obj&&v){obj.position.set(...v.pos);obj.rotation.set(...v.rot);obj.visible=v.visible;}}
 const tools=['driver','hammer','hexkey'];const active=action.tracks.find(tr=>!tools.includes(tr.id)&&playback.t.current>=tr.start&&playback.t.current<=tr.end)??action.tracks.find(tr=>!tools.includes(tr.id));const obj=active?objects.current[active.id]:null;guideLine.visible=false;if(active&&obj&&active.to.visible){const piece=PIECES.find(p=>p.id===active.id);const start=obj.getWorldPosition(new THREE.Vector3()),end=new THREE.Vector3(...active.to.pos);const parent=piece?.parent?objects.current[piece.parent]:null;parent?.localToWorld(end);if(start.distanceTo(end)>.02){guideLine.geometry.setFromPoints([start,end]);guideLine.computeLineDistances();guideLine.visible=true;}}if(obj&&label.current){obj.updateWorldMatrix(true,false);const at=obj.getWorldPosition(new THREE.Vector3());if(close&&active){at.set(...active.to.pos);const piece=PIECES.find(p=>p.id===active.id);if(piece?.parent)objects.current[piece.parent]?.localToWorld(at);}
 if(marker.current){const piece=PIECES.find(p=>p.id===active?.id);marker.current.visible=close&&!!piece?.code&&piece.kind!=='cover';marker.current.position.copy(at);marker.current.quaternion.copy(camera.quaternion);}
 label.current.position.copy(at).add(new THREE.Vector3(0,.06,0));const piece=PIECES.find(p=>p.id===active?.id);if(textRef.current)textRef.current.textContent=(close?'Target: ':'')+(piece?.label??'Part')+(piece?.code?' · '+piece.code:'');if(close&&auto.current&&controls.current){const c=controls.current;const offset=camera.position.clone().sub(c.target);c.target.lerp(at,Math.min(1,delta*3));camera.position.copy(c.target).add(offset);c.update();}}if(playback.playing.current||close&&auto.current)invalidate();});
 function nodes(parent:string):ReactNode{return children[parent]?.map(p=><group key={p.id} ref={el=>{if(el)objects.current[p.id]=el;}} onClick={e=>{e.stopPropagation();onPart(p.label+(p.code?' · hardware '+p.code:''));}}>{p.kind==='panel'?<group><Panel piece={p} highlighted={currentIds.has(p.id)} context={p.parent==='frame'}/></group>:p.kind==='group'?null:['driver','hammer','hexkey'].includes(p.id)?<Tool kind={p.kind}/>:<Hardware piece={p} highlighted={currentIds.has(p.id)}/>} {nodes(p.id)}</group>);}
 return <>{nodes('root')}<primitive object={guideLine}/><mesh ref={marker} visible={false}><torusGeometry args={[.017,.0015,8,32]}/><meshBasicMaterial color="#007ab0" depthTest={false}/></mesh><group ref={label}><Html center zIndexRange={[10,0]}><span ref={textRef} className="viewer-label"/></Html></group><ContactShadows position={[0,-.002,0]} opacity={.3} scale={5} blur={2} far={2}/></>;
}
class Boundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true};}render(){return this.state.failed?<div className="viewer-fallback">The 3D view is unavailable. Follow the written steps and original diagram.</div>:this.props.children;}}
export function SmastadViewer({animationId,replayToken,onAnimationFinished,prepared=true,closeUp=false,xray=false,finishToken=0,onReplay}:AssemblyViewerProps){
 const action=SM_ACTIONS.find(a=>animationId===a.id||animationId.startsWith(a.id+'-'));const inspect=animationId.endsWith('-inspect');const prefs=useBuilderPreferences();const t=useRef(0),playing=useRef(prefs.autoplay),invalidate=useRef<()=>void>(()=>{}),speed=useRef(prefs.speed);speed.current=prefs.speed;const [value,setValue]=useState(0),[isPlaying,setIsPlaying]=useState(playing.current),[close,setClose]=useState(animationId.endsWith('-detail')),[part,setPart]=useState('');const controls=useRef<Controls|null>(null);const completed=useRef(false),last=useRef(0);
 useEffect(()=>{t.current=window.matchMedia('(prefers-reduced-motion: reduce)').matches?1:0;playing.current=prefs.autoplay&&prepared&&!inspect&&t.current<1;setIsPlaying(playing.current);setValue(t.current);setClose(animationId.endsWith('-detail'));completed.current=false;invalidate.current();},[animationId,replayToken,prefs.autoplay,inspect,prepared]);
 useEffect(()=>{setClose(closeUp||animationId.endsWith("-detail"));},[closeUp,animationId]);
 useEffect(()=>{if(finishToken){t.current=1;playing.current=false;setIsPlaying(false);setValue(1);invalidate.current();}},[finishToken]);
 const pb:Playback={t,playing,invalidate,speed,onTick:n=>{const now=performance.now();if(now-last.current>90||n===1){setValue(n);last.current=now;}if(n===1&&!completed.current){completed.current=true;setIsPlaying(false);onAnimationFinished?.();}}};
 if(!action)return <div className="viewer-fallback">This action is unavailable.</div>;
 function play(){if(t.current>=1){t.current=0;completed.current=false;}playing.current=!playing.current;setIsPlaying(playing.current);invalidate.current();}
 return <div className="viewer smastad-viewer"><div className="viewer-canvas" role="img" aria-label={`Animated SMÅSTAD action: ${action.title}. Drag to rotate; scroll to zoom.`}><Boundary><Canvas shadows frameloop="demand" dpr={[1,1.75]} camera={{position:[1.7,1.5,2.1],fov:38,near:.01,far:30}}><AssemblyRoom studio={prefs.scene==='focus'}/><OrbitControls ref={controls} makeDefault enableDamping minDistance={.15} maxDistance={6} target={[0,.36,0]} maxPolarAngle={Math.PI/2-.025}/><Suspense fallback={null}><XrayContext.Provider value={xray}><Scene action={action} playback={pb} inspect={inspect} close={close} controls={controls} onPart={setPart}/></XrayContext.Provider></Suspense><Bridge target={invalidate}/></Canvas></Boundary></div><div className="viewer-controls"><button className="vbtn" onClick={play} disabled={inspect||!prepared}>{isPlaying?'Pause':'Play'}</button><button className="vbtn" onClick={()=>{onReplay?.();t.current=0;playing.current=true;completed.current=false;setIsPlaying(true);invalidate.current();}} disabled={inspect||!prepared}>Replay</button><input aria-label="Animation position" className="smastad-scrub" type="range" min={0} max={1} step={.01} value={value} onChange={e=>{t.current=Number(e.target.value);playing.current=false;setIsPlaying(false);setValue(t.current);invalidate.current();}} disabled={inspect||!prepared}/><button className="vbtn" aria-pressed={close} onClick={()=>setClose(!close)}>{close?'Whole assembly':'Close-up'}</button></div><p className="viewer-hint">{part||'Select a part to inspect its name and hardware code'} · {prefs.speed}× pace</p></div>;
}
function Bridge({target}:{target:React.MutableRefObject<()=>void>}){const invalidate=useThree(s=>s.invalidate);useEffect(()=>{target.current=invalidate;invalidate();},[target,invalidate]);return null;}
