export type ProductId = 'dresser' | 'bed' | 'loft' | 'wardrobe';
export type Tool = 'screwdriver' | 'hammer' | 'hand' | 'drill' | 'check' | 'hex' | 'flat' | 'pliers' | 'hexBed';
export interface ProductStep { number: number; page: number; title: string; tool: Tool; stage: number; }
export interface Product { id: ProductId; name: string; description: string; document: string; pages: number; warning: string; steps: ProductStep[]; }
const steps=(rows:[number,number,string,Tool,number][]):ProductStep[]=>rows.map(([number,page,title,tool,stage])=>({number,page,title,tool,stage}));
export const PRODUCTS: Product[] = [
 {id:'bed',name:'VIHALS',description:'White bed frame',document:'AA-2573514-1',pages:16,warning:'Two people are shown for joining the frame. Follow the support and slat orientation diagrams.',steps:steps([
 [1,4,'Place the first panel fittings','hand',0],[2,4,'Hand-turn the connector bolts','hand',0],[3,5,'Insert the rail dowels','hand',0],[4,5,'Orient and place the cam locks','hand',0],[5,6,'Join the frame with a second person','hand',1],[6,7,'Fit the end panel','hand',1],[7,7,'Place the connectors in the indicated orientation','hand',1],[8,8,'Tighten the corners using the supplied key','hexBed',1],[9,9,'Fit the support rails in the shown orientation','screwdriver',2],[10,10,'Fit the centre-support brackets','screwdriver',2],[11,11,'Prepare and fit the centre support','screwdriver',2],[12,12,'Install the diagonal braces','screwdriver',3],[13,13,'Position the centre rail','hand',3],[14,13,'Secure the centre rail ends','hand',3],[15,14,'Fit the slat retaining hardware','screwdriver',3],[16,15,'Place and retain the slatted base','hand',4]])},
 {id:'wardrobe',name:'RAKKESTAD',description:'Black-brown wardrobe · three doors',document:'AA-2213871-2',pages:32,warning:'Secure this wardrobe to the wall. Check the supplied wall fasteners against the wall types shown on page 24. Use a second person for lifting.',steps:steps([
 [1,7,'Prepare the side-panel hardware','screwdriver',0],[2,8,'Prepare the shelf and divider dowels','hand',0],[3,8,'Prepare the small panels','hand',0],[4,9,'Join the divider structure','hand',1],[5,9,'Seat the panel dowels','hand',1],[6,10,'Fit the threaded fittings with pliers','pliers',1],[7,10,'Add the panel connectors','screwdriver',1],[8,11,'Join the side to the dividers','hex',1],[9,11,'Lock the first side connections','hex',1],[10,12,'Position the second side panel','hand',1],[11,12,'Seat the second side dowels','hex',1],[12,13,'Secure the side connections','hex',1],[13,13,'Fit the remaining side connectors','hex',1],[14,14,'Prepare the long base rails','hand',2],[15,14,'Fit the rail fittings','screwdriver',2],[16,15,'Position the long rail','hand',2],[17,15,'Position the second rail','hand',2],[18,16,'Secure the long rails','hex',2],[19,17,'Install the base fittings','screwdriver',2],[20,18,'Identify the rear panel orientation','check',2],[21,18,'Position the rear-panel sections','hand',2],[22,19,'Align the rear panels','hand',2],[23,19,'Fasten the rear panels','hammer',2],[24,20,'Nail the rear-panel retainers','hammer',2],[25,21,'Secure the rear-panel retainers','screwdriver',2],[26,21,'Raise the wardrobe with a second person','hand',3],[27,22,'Check upright placement and level','check',3],[28,23,'Install the wall-restraint brackets','screwdriver',3],[29,24,'Choose the wall-fixing method shown for your wall','check',3],[30,25,'Install suitable wall fixings','drill',3],[31,25,'Secure the wall restraint','screwdriver',3],[32,26,'Prepare the interior fittings','screwdriver',3],[33,26,'Install shelf fittings','screwdriver',3],[34,27,'Fit the hanging rail','hand',3],[35,27,'Install the door hinges','screwdriver',4],[36,28,'Hang the doors on their hinges','hand',4],[37,29,'Fit the door handles','screwdriver',4],[38,30,'Install the final fittings','hand',4]])},
 {id:'dresser',name:'FÅGELFJÄLLET',description:'Dark gray-blue dresser · six drawers',document:'AA-2622651-2',pages:40,warning:'The manual requires wall anchoring and includes a drawer interlock. Complete the restraint and interlock checks before use.',steps:steps([
 [1,7,'Prepare the first frame connectors','screwdriver',0],[2,8,'Prepare the side-panel hardware','screwdriver',0],[3,9,'Prepare the rails and dowels','hand',0],[4,9,'Attach the frame rails','hand',1],[5,10,'Lock the rail connectors','flat',1],[6,10,'Position the joining panel','hand',1],[7,11,'Lock the panel connections','flat',1],[8,11,'Fit the next panel','hand',1],[9,12,'Prepare the large panel fittings','screwdriver',1],[10,12,'Fit the panel connectors','screwdriver',1],[11,13,'Position the prepared panel','hand',1],[12,13,'Fit the remaining frame panel','hand',1],[13,14,'Tighten the frame cam locks','flat',1],[14,14,'Secure the frame connection with the supplied key','hex',1],[15,15,'Slide the rear panel into position','hand',2],[16,16,'Fit the rear-panel retainers','hand',2],[17,16,'Install the shown interlock component','screwdriver',2],[18,17,'Fit the first restraint/interlock fitting','hand',2],[19,17,'Fit the remaining fittings','hand',2],[20,18,'Install the long connector fitting','hand',2],[21,18,'Check the illustrated fitting orientation','check',2],[22,19,'Prepare the base component','screwdriver',2],[23,19,'Orient and prepare the matching component','screwdriver',2],[24,20,'Position the base component','hand',2],[25,20,'Fit the base assembly','hand',2],[26,21,'Lock the base connections','flat',2],[27,21,'Secure the remaining base fittings','screwdriver',2],[28,22,'Fit the base/end fittings','hand',2],[29,23,'Stand the dresser and check fittings','hand',3],[30,23,'Position the dresser at the wall','check',3],[31,24,'Choose wall-fixing method A, B or C','check',3],[32,25,'Prepare suitable wall fixings','drill',3],[33,25,'Seat the supplied wall plugs for method A or B','hammer',3],[34,29,'Secure the restraint brackets','screwdriver',3],[35,30,'Prepare the drawer-front connectors','screwdriver',4],[36,31,'Fit the small drawer sides','hand',4],[37,31,'Fit the large drawer sides','hand',4],[38,32,'Lock the drawer-side connections','flat',4],[39,32,'Slide in the drawer bottom','hand',4],[40,33,'Fit the illustrated drawer-back fitting','hammer',4],[41,34,'Orient the drawer assembly','hand',4],[42,34,'Fit the drawer locking component','hand',4],[43,35,'Place the drawer-back fasteners','hand',4],[44,35,'Fit the remaining drawer fasteners','flat',4],[45,36,'Attach the drawer hardware','screwdriver',4],[46,36,'Fit the drawer handles','screwdriver',4],[47,37,'Install drawers in the shown sequence','hand',5],[48,37,'Test the drawer interlock as illustrated','check',5]])},
 {id:'loft',name:'SMÅSTAD',description:'Loft-bed desk and storage additions',document:'AA-2200883-3',pages:44,warning:'This PDF starts with an existing loft-bed frame. It is not the complete loft-bed frame assembly manual. Choose a desk configuration before following the applicable diagrams.',steps:steps([
 [1,5,'Prepare the storage-unit connectors','screwdriver',0],[2,5,'Position the storage-unit panels','hand',0],[3,6,'Lock the storage-unit connections','screwdriver',0],[4,6,'Fit the top-panel dowels','hand',0],[5,7,'Position the storage-unit top','hand',1],[6,8,'Lock the top-panel connectors','screwdriver',1],[7,8,'Fit the remaining top fittings','hand',1],[8,10,'Prepare the desktop fittings','screwdriver',2],[9,10,'Position the desktop for the selected layout','hand',2],[10,11,'Secure desktop to storage unit','screwdriver',2],[11,11,'Fit the illustrated cable opening','hand',2],[12,12,'Position the desk and fit the illustrated connectors','screwdriver',3],[13,12,'Secure the desk connections','screwdriver',3],[14,13,'Fit the side hole covers','hand',3],[15,13,'Prepare the shelf supports','hand',3],[16,14,'Place the illustrated hole covers','hand',3],[17,15,'Place the remaining hole covers','hand',4]])}
];
export const productById=(id:string)=>PRODUCTS.find(p=>p.id===id);
export const TOOL_INFO: Record<Tool,{name:string;source:string;guidance:string[]}>={
 screwdriver:{name:'Cross-head manual screwdriver · match the illustrated head',source:'User-supplied tool; fasteners come from the hardware pack.',guidance:['Identify the exact fastener in the diagram before selecting a driver.','Use a cross-head bit that fits the illustrated head fully. Do not guess the screw size.','Keep the driver aligned with the screw. Turn slowly; stop when seated without stripping the head.','For cam locks, follow the arrow and alignment in the manual. Do not treat a cam lock as an ordinary screw.']},
 hammer:{name:'Hammer · only where the manual shows it',source:'User-supplied tool; use the specified nail or dowel from the hardware pack.',guidance:['Support the panel on a protected surface.','Align the specified fastener with the diagram. Keep fingers clear of the striking area.','Use light controlled taps. Do not hammer a screw or cam lock.']},
 hexBed:{name:'Supplied hex key · part 100092',source:'Included tool shown in the VIHALS hardware inventory on page 3.',guidance:['Select key 100092 and fastener 105236 as shown on manual page 8.','Seat the key fully in the socket; support and align the frame joint.','Turn the key by hand in the indicated direction. Do not substitute a screwdriver.']},
 pliers:{name:'Pliers · for the illustrated threaded fitting',source:'User-supplied pliers, shown on RAKKESTAD page 10.',guidance:['Select fitting 109837 from the provided hardware.','Grip the fitting as illustrated and turn it into the indicated hole.','Keep it aligned and avoid crushing the fitting or using pliers on other hardware.']},
 hex:{name:'Supplied hex key · part 100001',source:'Included tool: match key 100001 to the socket-head fastener shown.',guidance:['Find the hex key marked 100001 in the hardware inventory.','Seat the short end fully in the socket head, keeping it aligned.','Turn the longer arm by hand in the direction shown. Do not use a screwdriver or powered driver on this connection.']},
 flat:{name:'Flat-head manual screwdriver · cam-lock slot',source:'User-supplied flat-head screwdriver; cam hardware is included.',guidance:['Orient the cam opening toward its mating bolt as shown in the diagram.','Seat a flat blade in the slot and turn in the direction shown until the joint locks.','Use the indicated cam movement; do not keep turning or force the joint.']},
 hand:{name:'Hand placement · no powered tool for this action',source:'Select the panel, dowel or fitting shown in the manual.',guidance:['Compare the panel shape and hole pattern with the manual.','Align the mating parts before pressing them together.','Use the second person where illustrated. If a part resists, recheck orientation rather than forcing it.']},
 drill:{name:'Drill / wall-fixing tools · selected for your wall',source:'User-supplied drill. These manuals include wall fixings for the illustrated wall types; confirm suitability.',guidance:['Choose the fixing method shown for your wall type. The app cannot identify your wall or prescribe a bit diameter.','Use the supplied fixings only where suitable for the illustrated wall type; check for hidden cables and pipes before drilling.','Follow the drill and fixing manufacturers’ instructions. Ask a qualified person if unsure.','Do not use a drill to drive furniture cam locks or substitute for hand tightening.']},
 check:{name:'Inspect the diagram before proceeding',source:'No fastening demonstration needed for this check.',guidance:['Compare the assembled parts with the manual illustration.','Review any warning or alternative configuration on this page.','Confirm the physical check yourself; animation playback does not complete a step.']}
};
export function manualPage(p:Product,s:ProductStep,layout:number,wall:string){
 if(p.id==='loft'&&s.number>=8){const maps:number[][]=[[10,10,11,11,12,12,13,13,14,15],[16,16,17,17,18,18,19,19,20,21],[22,23,23,24,24,25,25,26,27,28],[32,32,33,33,34,34,35,36,37,38],[32,32,33,33,34,34,35,39,40,41],[22,23,23,24,24,25,25,29,30,31]];return maps[layout]?.[s.number-8]??s.page;}
 if(p.id==='dresser'&&s.number===32)return wall==='A'?25:wall==='B'?26:28;
 if(p.id==='dresser'&&s.number===33)return wall==='A'?25:wall==='B'?27:28;
 return s.page;
}

export function productSteps(p:Product,wall:string){return p.steps.filter(s=>!(p.id==='dresser'&&wall==='C'&&s.number===33));}

/** Hardware callouts transcribed from inspected manual diagrams; omitted when not verified. */
export const HARDWARE_CALLOUTS: Partial<Record<ProductId,Record<number,string>>> = {
 bed:{1:'6 × fitting 10121774',2:'4 × connector 114671',3:'8 × dowel 101359',4:'4 × cam 114670; orient the opening as illustrated',7:'4 × fitting 104895; keep the illustrated orientation',8:'4 × fastener 105236; supplied key 100092',9:'Use the left/right rail orientation shown on page 9',15:'4 × retaining fitting 10096286 and screw 105163'},
 wardrobe:{6:'4 × threaded fitting 109837',7:'1 × screw 109041; bracket 103717. Do not substitute the longer screw shown crossed out.',8:'2 × socket screw 100219; key 100001',9:'2 × socket screw 100219; key 100001',11:'2 × socket screw 100219',12:'4 × socket screw 100219',13:'2 × socket screw 100219',18:'4 × socket screw 100219',19:'1 × screw 109041; do not substitute the longer screw.',24:'44 × nail 405950, through rear-panel retainers as illustrated',32:'2 × screw 109049 and washer 100823',33:'2 × screw 105248 with fitting 157308'},
 dresser:{1:'10 × connector 113831 from pack 1',10:'6 × connector 113831',13:'4 × cam 119250 / 119252',14:'1 × socket screw 100217; key 100001',16:'4 × fitting 151708 and 4 × retaining pin 151707',17:'1 × screw 100359 with component 10136453',18:'1 × fitting 10093081',19:'9 × fitting 10093081',20:'10 × cap 10093082',22:'3 × cam 119250 / 119252',23:'3 × cam 119250 / 119252',24:'2 × dowel 101345',26:'2 × cam 119250 / 119252',27:'2 × screw 105811',35:'4 × connector 130449 from pack 2',38:'4 × cam 119030 / 118224 / 117434',40:'1 × fitting 10040422 on each large drawer; follow the crossed-out orientation warning',42:'1 × locking fitting 10133139',43:'4 × fastener 145718 / 159553 / 10120234',44:'4 × cam 119030 / 118224 / 117434',45:'6 × screw 146114 per illustrated drawer assembly',46:'2 × screw 119976 for each handle'},
 loft:{1:'8 × connector 114613',3:'2 × cam 113434',4:'8 × dowel; match the hardware diagram',6:'4 × cam 113434',8:'6 × connector 114613',10:'4 × cam 113434',11:'1 × cable opening fitting 155056',12:'2 × connector 114613',13:'2 × cam 113434',14:'6 × cap 139251',16:'Caps 147054 in the positions shown for your layout',17:'Caps 124257 / 147054; follow the selected configuration'}
};
