import {useState} from 'react';
/** Optional explanatory diagrams supplement the prepared 3D action, never replace the source manual. */
export function ConnectionTeaching({tool,smastad,twoPeople}:{tool:string;smastad:boolean;twoPeople:boolean}){
 const [lesson,setLesson]=useState<'tool'|'mistake'|'parts'|'people'>('tool');
 const hex=/hex|Allen|100092/i.test(tool),hammer=/hammer/i.test(tool),hands=/hand|none|no tool/i.test(tool);
 return <div className="connection-teaching"><div className="lesson-tabs" aria-label="Extra guidance">
 {(['tool','mistake','parts',...(twoPeople?['people']:[])] as const).map(k=><button key={k} className="vbtn" aria-pressed={lesson===k} onClick={()=>setLesson(k as typeof lesson)}>{({tool:'How to use the tool',mistake:'Common mistake',parts:'Compare parts',people:'Where to hold'})[k]}</button>)}
 </div>
 {lesson==='tool'&&<><svg viewBox="0 0 360 150" role="img" aria-label={hands?'Align by hand':hex?'Insert the short end fully, then turn the long arm':hammer?'Light taps seat the fitting': 'Seat the screwdriver straight in the head, then turn'}><rect x="30" y="119" width="300" height="15" rx="3" fill="#e2d9c9"/><circle cx="180" cy="119" r="9" fill="#748a96"/><g className={hammer?'teaching-tap':hands?'teaching-seat':'teaching-turn'} style={{transformOrigin:'180px 110px'}}>{hex?<path d="M180 113V50H245" fill="none" stroke="#688190" strokeWidth="8"/>:hammer?<><path d="M180 95V25" stroke="#ac8152" strokeWidth="9"/><rect x="152" y="84" width="56" height="20" rx="3" fill="#688190"/></>:hands?<rect x="146" y="50" width="68" height="25" rx="5" fill="#e2d9c9"/>:<><path d="M180 113V65" stroke="#688190" strokeWidth="5"/><rect x="168" y="15" width="24" height="52" rx="9" fill="#315e70"/></>}</g></svg><p>{hands?'Line up the holes before lowering the part. Press gently; stop if it resists.':hex?'Insert the short end fully into the hex socket. Use the long arm to turn clockwise. Keep the key seated; stop when the joint is snug.':hammer?'Hold the fitting straight and use light taps. Stop once it is seated; do not strike the finished panel.':'Place the tip fully in the cross-shaped head. Hold the shaft straight along the screw axis and turn clockwise without forcing it.'}</p></>}
 {lesson==='mistake'&&<><svg viewBox="0 0 360 150" role="img" aria-label="A tilted screw misses the hole; align it straight before inserting"><rect x="40" y="115" width="280" height="20" fill="#e2d9c9"/><circle cx="180" cy="115" r="9" fill="#244454"/><g className="teaching-correct" style={{transformOrigin:'180px 110px'}}><path d="M180 45V108" stroke="#758b95" strokeWidth="7"/><path d="M167 45H193" stroke="#758b95" strokeWidth="5"/></g><text x="25" y="27" fill="#a34632">Tilted → stop</text><text x="231" y="27" fill="#28684d">Straight → fits</text></svg><p>Common mistake: pushing a connection in at an angle. The holes must line up first. Pull back, straighten the part, then insert gently. This is an illustrative alignment lesson.</p></>}
 {lesson==='parts'&&<div className="part-compare"><div><strong>{smastad?'114613':'LACK double-ended screw'}</strong><span>✚</span><p>{smastad?'Connector for cam-lock joints. Use the cross-head driver.':'Threaded at both ends. These four supplied screws serve the same purpose.'}</p></div><div><strong>{smastad?'100218':'Matching LACK screw'}</strong><span>{smastad?'⬡':'✚'}</span><p>{smastad?'Frame fixing with a hex socket. Use the supplied 100092 key.':'Do not choose by apparent screen length. Match both threaded ends to the manual.'}</p></div><small>Identify hardware by its code and head shape. Illustrations are not actual-size measurements.</small></div>}
 {lesson==='people'&&<><svg viewBox="0 0 360 150" role="img" aria-label="One person supports the desktop from below, while another guides the outer end"><rect x="70" y="65" width="230" height="15" fill="#e2d9c9"/><path d="M115 125V90L140 83M260 125V90L280 83" fill="none" stroke="#315e70" strokeWidth="12" strokeLinecap="round"/><text x="45" y="30">Support underneath</text><text x="225" y="145">Guide outer end</text></svg><p>Ask a helper to support the desktop from underneath while you guide its outer end into the frame. Keep fingers away from the closing joint. These hold points are added guidance.</p></>}
 </div>;
}
